In [ ]:
import pandas as pd

df = pd.read_csv("/content/sample_data/preprocessed_shoppers.csv")
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,-0.702302,-0.460019,-0.398824,-0.246257,-0.696218,-0.628793,3.969402,3.434394,-0.318962,-0.31024,2,1,1,1,1,1,0,0
1,-0.702302,-0.460019,-0.398824,-0.246257,-0.673793,-0.595451,-0.450137,1.268054,-0.318962,-0.31024,2,2,2,1,2,1,0,0
2,-0.702302,-0.460019,-0.398824,-0.246257,-0.696218,-0.628793,3.969402,3.434394,-0.318962,-0.31024,2,4,1,9,3,1,0,0
3,-0.702302,-0.460019,-0.398824,-0.246257,-0.673793,-0.627404,0.654748,2.134590,-0.318962,-0.31024,2,3,2,2,4,1,0,0
4,-0.702302,-0.460019,-0.398824,-0.246257,-0.494387,-0.301889,-0.008183,0.184884,-0.318962,-0.31024,2,3,3,1,4,1,1,0

In [ ]:
df['Weekend'] = df['Weekend'].astype(int)
df['Revenue'] = df['Revenue'].astype(int)

In [ ]:
df = pd.get_dummies(df, columns=['Month', 'VisitorType'], drop_first=True)

In [ ]:
from sklearn.preprocessing import StandardScaler

numerical_cols = [
    'Administrative', 'Administrative_Duration',
    'Informational', 'Informational_Duration',
    'ProductRelated', 'ProductRelated_Duration',
    'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay'
]

scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [ ]:
X = df.drop('Revenue', axis=1)
y = df['Revenue']

In [ ]:
X.to_csv("X_processed.csv", index=False)
y.to_csv("y_processed.csv", index=False)

print("DONE ✅")

DONE ✅

In [ ]:
X.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,Month_5,Month_6,Month_7,Month_8,Month_9,Month_10,Month_11,Month_12,VisitorType_2,VisitorType_3
0,-0.702302,-0.460019,-0.398824,-0.246257,-0.696218,-0.628793,3.969402,3.434394,-0.318962,-0.31024,...,False,False,False,False,False,False,False,False,False,False
1,-0.702302,-0.460019,-0.398824,-0.246257,-0.673793,-0.595451,-0.450137,1.268054,-0.318962,-0.31024,...,False,False,False,False,False,False,False,False,False,False
2,-0.702302,-0.460019,-0.398824,-0.246257,-0.696218,-0.628793,3.969402,3.434394,-0.318962,-0.31024,...,False,False,False,False,False,False,False,False,False,False
3,-0.702302,-0.460019,-0.398824,-0.246257,-0.673793,-0.627404,0.654748,2.134590,-0.318962,-0.31024,...,False,False,False,False,False,False,False,False,False,False
4,-0.702302,-0.460019,-0.398824,-0.246257,-0.494387,-0.301889,-0.008183,0.184884,-0.318962,-0.31024,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Revenue, dtype: int64